### ISSUE TITLE
Top checkbox to select/unselect domains and identities ...

### ISSUE THREAD

**Issue by controlcde** [tonioo/modoboa#658]
A wish: I need the possibilty to multiselect domains or identities for example to multidelete them. And it would be nice if I could adjust the view (how many identities should show on one page).

**Comment by controlcde** [comment]
I can´t get it working. I´m using virtualenv ```/srv/venv/modoboa``` and after droping the database I go into the virtualenv and change into site-dir ```/srv/mailadmin``` to fire up the command

```
(modoboa)root:/srv/mailadmin# python manage.py syncdb --migrate --noinput
Syncing...
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/management/commands/syncdb.py", line 89, in handle_noargs
    db.connection_init()
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/db/mysql.py", line 183, in connection_init
    cursor = self._get_connection().cursor()
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/db/backends/__init__.py", line 162, in cursor
    cursor = util.CursorWrapper(self._cursor(), self)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/db/backends/__init__.py", line 132, in _cursor
    self.ensure_connection()
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/db/backends/__init__.py", line 127, in ensure_connection
    self.connect()
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/db/backends/__init__.py", line 115, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/db/backends/mysql/base.py", line 435, in get_new_connection
    conn = Database.connect(**conn_params)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1049, "Unknown database 'modoboa'")
```

And the command ```loaddata```could not found.

```
(modoboa)root:/srv/mailadmin# python loaddata initial_users.json
python: can't open file 'loaddata': [Errno 2] No such file or directory
```

**Comment by tonioo** [comment]
The first error says your database does not exist (have you created the "modoboa" database?).

The right way to launch the loaddata command is:

```shell
(modoboa)root:/srv/mailadmin# python manage.py loaddata initial_users.json
```

**Comment by controlcde** [comment]
@tonioo You´re right: I misunderstood your "After dropping your database, try to run the following commands". Now I´ve created the database and gave the modoboa database user full access but I get the following error after initial success:

```
FATAL ERROR - The following SQL query failed: ALTER TABLE `auth_user` ;
The error was: (1146, "Table 'modoboa.auth_user' doesn't exist")
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/management/commands/syncdb.py", line 103, in handle_noargs
    management.call_command('migrate', **options)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/migrators.py", line 93, in run_migration
    print(self.run_migration_error(migration))
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/migrators.py", line 325, in run_migration_error
    (self.format_backwards(migration), extra_info))
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/migrators.py", line 312, in format_backwards
    self.backwards(migration)()
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/modoboa-1.2.0-py2.7.egg/modoboa/extensions/admin/migrations/0005_increase_columns_length.py", line 15, in backwards
    raise RuntimeError("Cannot revert this migration")
RuntimeError: Cannot revert this migration
```

So I think I didn´t have to migrate any data if I drop the database, right?

But how would the default user *admin* with password and the *super admin* group created? The `python manage.py loaddata initial_users.json` said:

```Installed 2 object(s) from 1 fixture(s)``` but I could not find any user in the database.

**Comment by tonioo** [comment]
What do you mean by "after initial success" ? What commands did you run ?

**Comment by controlcde** [comment]
* With "after initial success" I mean that everything that will be started before the migration (from the manage.py) will be successfully executed (but I won´t paste the full output).

* I started the process with `(modoboa)root:/srv/mailadmin# python manage.py syncdb --migrate --noinput` like you wrote above.

**Comment by tonioo** [comment]
So you just launch this command and it fails, right ?

Could you paste the complete output ?

**Comment by controlcde** [comment]
Right, the command fails
```
(modoboa)root:/srv/mailadmin# python manage.py syncdb --migrate --noinput
Syncing...
Creating tables ...
Creating table auth_permission
Creating table auth_group_permissions
Creating table auth_group
Creating table django_content_type
Creating table django_session
Creating table django_site
Creating table south_migrationhistory
Creating table postfix_relay_domains_service
Creating table postfix_relay_domains_relaydomain
Creating table postfix_relay_domains_relaydomainalias
Creating table radicale_usercalendar
Creating table radicale_sharedcalendar
Creating table radicale_accessrule
Installing custom SQL ...
Installing indexes ...
Installed 0 object(s) from 0 fixture(s)
Migrating...
Running migrations for reversion:
 - Migrating forwards to 0008_auto__add_index_revision_date_created.
 > reversion:0001_initial
 > reversion:0002_auto__add_field_version_type
 > reversion:0003_auto__add_field_version_object_id_int
 > reversion:0004_populate_object_id_int
 - Migration 'reversion:0004_populate_object_id_int' is marked for no-dry-run.
 > reversion:0005_auto__add_field_revision_manager_slug
 > reversion:0006_remove_delete_revisions
 - Migration 'reversion:0006_remove_delete_revisions' is marked for no-dry-run.
 > reversion:0007_auto__del_field_version_type
 > reversion:0008_auto__add_index_revision_date_created
 - Loading initial data for reversion.
Installed 0 object(s) from 0 fixture(s)
Running migrations for core:
 - Migrating forwards to 0004_auto__chg_field_user_password.
 > core:0001_initial
 > admin:0001_initial
 > admin:0002_auto__del_field_alias_mbox
 - Migration 'admin:0002_auto__del_field_alias_mbox' is marked for no-dry-run.
 > admin:0003_auto__add_extension
 > admin:0004_add_permissions
 - Migration 'admin:0004_add_permissions' is marked for no-dry-run.
 > admin:0005_increase_columns_length
FATAL ERROR - The following SQL query failed: ALTER TABLE `auth_user` ;
The error was: (1146, "Table 'modoboa.auth_user' doesn't exist")
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/base.py", line 415, in handle
    return self.handle_noargs(**options)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/management/commands/syncdb.py", line 103, in handle_noargs
    management.call_command('migrate', **options)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/__init__.py", line 159, in call_command
    return klass.execute(*args, **defaults)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/Django-1.6.9-py2.7.egg/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/__init__.py", line 220, in migrate_app
    success = migrator.migrate_many(target, workplan, database)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/migrators.py", line 256, in migrate_many
    result = migrator.__class__.migrate_many(migrator, target, migrations, database)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/migrators.py", line 331, in migrate_many
    result = self.migrate(migration, database)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/migrators.py", line 133, in migrate
    result = self.run(migration, database)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/migrators.py", line 114, in run
    return self.run_migration(migration, database)
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/migrators.py", line 93, in run_migration
    print(self.run_migration_error(migration))
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/migrators.py", line 325, in run_migration_error
    (self.format_backwards(migration), extra_info))
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/migrators.py", line 312, in format_backwards
    self.backwards(migration)()
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/South-1.0.2-py2.7.egg/south/migration/migrators.py", line 60, in <lambda>
    return (lambda: direction(orm))
  File "/srv/venv/modoboa/local/lib/python2.7/site-packages/modoboa-1.2.0-py2.7.egg/modoboa/extensions/admin/migrations/0005_increase_columns_length.py", line 15, in backwards
    raise RuntimeError("Cannot revert this migration")
RuntimeError: Cannot revert this migration
```
Oh, and I forgot: I´m just using the git version from yesterday.

**Comment by tonioo** [comment]
Ok, I understand what's happening.

You can't use ```python manage.py syncdb --noinput``` for a fresh install (that's why I created the modoboa-admin command).

Instead of that, you need to (after a database drop):
1. Comment out the "south" line in INSTALLED_APPS
2. Run ```python manage.py syncdb```
3. Uncomment the "south" line in INSTALLED_APPS
4. Run ```python manage.py syncdb```
5. Run ```python manage.py migrate --fake```
6. Run ```python manage.py loaddata initial_users.json```

**Comment by controlcde** [comment]
Great! Now it works.

**Comment by controlcde** [comment]
But after all - it would be still nice to get the checkbox to select/unselect all domains and/or all identities. but if you don´t want this feature please close this issue. :accept:

**Comment by tonioo** [comment]
This issue was moved to modoboa/modoboa-admin#9
