### ISSUE TITLE
Upgrade from 1.2.1 to 1.3.3 unsuccessfull - SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by mrh666** [tonioo/modoboa#746]
Hi there,

Centos 6.6. Both python 2.6.6 and 2.7.10 are installed.
I has working version 1.2.1 of modoboa and decided to upgrade...

I upgraded modoboa from 1.2.1 to 1.3.3 by pip install modoboa==1.3.3. It was upgraded together with all deps. When I trying to deploy a new site I've get an error:

```
$ modoboa-admin.py deploy modoboa_site --collectstatic --dburl default:mysql://USER:PASS@localhost:3306/modoboa

Traceback (most recent call last):
  File "/usr/bin/modoboa-admin.py", line 4, in <module>
    from modoboa.core.commands import handle_command_line
  File "/usr/lib/python2.6/site-packages/modoboa/core/__init__.py", line 3, in <module>
    from django.core.urlresolvers import reverse
  File "/usr/lib/python2.6/site-packages/django/core/urlresolvers.py", line 16, in <module>
    from django.http import Http404
  File "/usr/lib/python2.6/site-packages/django/http/__init__.py", line 4, in <module>
    from django.http.response import (
  File "/usr/lib/python2.6/site-packages/django/http/response.py", line 13, in <module>
    from django.core.serializers.json import DjangoJSONEncoder
  File "/usr/lib/python2.6/site-packages/django/core/serializers/__init__.py", line 23, in <module>
    from django.core.serializers.base import SerializerDoesNotExist
  File "/usr/lib/python2.6/site-packages/django/core/serializers/base.py", line 6, in <module>
    from django.db import models
  File "/usr/lib/python2.6/site-packages/django/db/__init__.py", line 4, in <module>
    from django.db.utils import (DEFAULT_DB_ALIAS, DataError, OperationalError,
  File "/usr/lib/python2.6/site-packages/django/db/utils.py", line 190
    TEST_SETTING_RENAMES_REVERSE = {v: k for k, v in TEST_SETTING_RENAMES.items()}
                                           ^
SyntaxError: invalid syntax
```

Same error I've got now even when I try to run ```modoboa-admin.py help deploy```

```
$ pip list
argparse (1.3.0)
chardet (2.3.0)
click (3.3)
dj-database-url (0.3.0)
Django (1.7.8)
django-reversion (1.8.5)
django-versionfield2 (0.3.3)
django-xforwardedfor-middleware (1.0)
dnspython (1.11.1)
elasticsearch (1.4.0)
elasticsearch-curator (3.0.1)
ethtool (0.6)
factory-boy (2.5.2)
gunicorn (18.0)
importlib (1.0.3)
iniparse (0.3.1)
iwlib (1.0)
LEPL (5.1.3)
lxml (3.4.3)
mod-python (3.5.0)
modoboa (1.3.3)
MySQL-python (1.2.3rc1)
passlib (1.6.2)
pip (7.0.3)
py-rrdtool (0.2.1)
pycrypto (2.6.1)
pycurl (7.19.0)
pygpgme (0.1)
pyinotify (0.9.1)
python-ldap (2.3.10)
python-memcached (1.43)
requests (2.6.0)
rfc6266 (0.0.4)
setuptools (14.3.1)
sievelib (0.8)
South (1.0.2)
Twisted (14.0.2)
txAMQP (0.6.2)
urlgrabber (3.9.1)
urllib3 (1.10.2)
uWSGI (2.0.10)
virtualenv (1.11.6)
whisper (0.9.12)
yum-metadata-parser (1.1.2)
zope.interface (4.1.1)
```

I try to rollback to Django 1.6.11 and I've got another error:

```
$ modoboa-admin.py deploy modoboa_site --collectstatic --dburl default:mysql://USER:PASS@localhost:3306/modoboa

Traceback (most recent call last):
  File "/usr/bin/modoboa-admin.py", line 7, in <module>
    handle_command_line()
  File "/usr/lib/python2.6/site-packages/modoboa/core/commands/__init__.py", line 95, in handle_command_line
    commands[args.command](commands, verbose=args.verbose).run(remaining)
  File "/usr/lib/python2.6/site-packages/modoboa/core/commands/__init__.py", line 36, in run
    self.handle(args)
  File "/usr/lib/python2.6/site-packages/modoboa/core/commands/deploy.py", line 177, in handle
    django.setup()
AttributeError: 'module' object has no attribute 'setup'
```

Can you please help me to determine what did I break and how to fix it?

Thank you!

**Comment by tonioo** [comment]
Hi,

you need to run python 2.7 and Django 1.7. Your stack trace shows that you're using python 2.6.

**Comment by mrh666** [comment]
Antoine,

You was absolutely right. Switching default system python to 2.7 in alternatives did the trick.

Thank you.
