### ISSUE TITLE
manage.py: Unknown command: 'generate_rights'

### ISSUE THREAD

**Issue by Fulviuus** [tonioo/modoboa#772]
I have installed modoboa using the installer.
The webadmin now seems to run ok, but I am unable to receive any email after configuring domain & users - I have done some investigation and I have noticed that I am being spammed from cron with this message:

```
Subject: Cron <root@columbia>    $PYTHON $INSTANCE/manage.py generate_rights

Unknown command: 'generate_rights'
Type 'manage.py help' for usage.
```

Seems like Django is not installed?
I have set it up manually and tried to run ./manage.py help as suggested but now I get:

```
root@columbia:/srv/modoboa/instance# ./manage.py help
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 303, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 92, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/srv/modoboa/instance/instance/settings.py", line 207, in <module>
    from modoboa_amavis.settings import *
ImportError: No module named modoboa_amavis.settings

```

I'm giving up.

**Comment by Fulviuus** [comment]
Update: I am not sure that is the only issue I am having with the installation.
The mail log shows this bit when receiving an email:

```
Oct 30 20:19:06 columbia postfix/postscreen[2464]: CONNECT from [74.125.82.44]:36353 to [178.62.123.35]:25
Oct 30 20:19:06 columbia postfix/postscreen[2464]: warning: connect to private/tlsproxy service: No such file or directory
Oct 30 20:19:06 columbia postfix/postscreen[2464]: HANGUP after 0.03 from [74.125.82.44]:36353 in tests after SMTP handshake
Oct 30 20:19:06 columbia postfix/postscreen[2464]: DISCONNECT [74.125.82.44]:36353
```

Is there also a problem with postfix tlsproxy?

**Comment by tonioo** [comment]
Hi,

the CRON issue happens because the modoboa-radicale extension is not installed. Edit the /etc/cron.d/modoboa file and comment the line containing generate_rights.

I don't know what is the problem with tlsproxy yet, I'll look into it.

**Comment by tonioo** [comment]
Just enable the tlsproxy, look into the master.cf file and uncomment the appropriate line.

**Comment by ezhishui** [comment]
I have met the same problem.The tlsproxy in master.cf was enabled all the time.And root@mydomain received lots of emails from Cron Daemon,about one email every 2 minutes.

**Comment by Whichcraft** [comment]
[root@mail instance]# su modoboa
$ /bin/bash
modoboa@mail:~/instance$ ./manage.py generate_rights
Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.managemen

Django is not available. installer did not install it.

**Comment by Whichcraft** [comment]
after apt-get install python-django

modoboa@mail:~/instance$ ./manage.py generate_rights
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/dist-packages/django/conf/__init__.py", line 98, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'instance.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named modoboa_amavis.settings

**Comment by Whichcraft** [comment]
installer.cfg is missing modoboa-radicale extension

original:

extensions = modoboa-amavis modoboa-pdfcredentials modoboa-postfix-autoreply modoboa-sievefilters modoboa-stats modoboa-webmail

better

extensions = modoboa-amavis modoboa-pdfcredentials modoboa-postfix-autoreply modoboa-sievefilters modoboa-stats modoboa-webmail modoboa-radicale
