### ISSUE TITLE
Migration from 1.2 to relaydomains-1.1 fails

### ISSUE THREAD

**Issue by tonioo** [tonioo/modoboa#800]
_From @andrewyager on November 6, 2015 9:56_

I'm having lots of issues migrating from 1.2 to relaydomains-1.1.

Most notably, the migration fails at step 0004:

```
  Applying modoboa_admin_relaydomains.0004_auto_20150506_1609...Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 102, in apply_migration
    migration.apply(project_state, schema_editor)
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 108, in apply
    operation.database_forwards(self.app_label, schema_editor, project_state, new_state)
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 139, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 470, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type, old_db_params, new_db_params, strict)
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 615, in _alter_field
    params,
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/django/db/backends/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/opt/spamcloud-gui/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.IntegrityError: (1062, "Duplicate entry '0' for key 'domain_id'")
```

From what I can tell this is failing on the final step of the migration where it is altering the table and migrating the domains from the relay_domain table to the domain table. I've been attempting to work around this for a little while but I'm not seeing an easy way to modify this migration to get around this? Any suggestions?

_Copied from original issue: modoboa/modoboa-admin-relaydomains#7_

**Comment by tonioo** [comment]
Hi, it looks like you have duplicated entries into you postfix_relay_domains_relaydomain table.

**Comment by tonioo** [comment]
_From @andrewyager on November 8, 2015 13:33_

Hi,

It doesn't appear that way:

```
mysql> SELECT count(name) as TOTALDOMAINS, count(DISTINCT `name`) as UNIQUENAMES from postfix_relay_domains_relaydomain;
+--------------+-------------+
| TOTALDOMAINS | UNIQUENAMES |
+--------------+-------------+
|           83 |          83 |
+--------------+-------------+
1 row in set (0.00 sec)
```

The `targethost` is not unique, but the "name" is.

**Comment by tonioo** [comment]
Check you check your table to find all records with a domain_id column set to 0 please ?

**Comment by tonioo** [comment]
_From @andrewyager on November 8, 2015 13:46_

In 1.2 there is no domain_id column:

```
CREATE TABLE `postfix_relay_domains_relaydomain` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dates_id` int(11) NOT NULL,
  `name` varchar(100) NOT NULL,
  `target_host` varchar(255) NOT NULL,
  `service_id` int(11) NOT NULL,
  `enabled` tinyint(1) NOT NULL,
  `verify_recipients` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  KEY `postfix_relay_domains_relaydomain_7263d97e` (`dates_id`),
  KEY `postfix_relay_domains_relaydomain_91a0ac17` (`service_id`),
  CONSTRAINT `dates_id_refs_id_0ae34bde` FOREIGN KEY (`dates_id`) REFERENCES `admin_objectdates` (`id`),
  CONSTRAINT `service_id_refs_id_4579196f` FOREIGN KEY (`service_id`) REFERENCES `postfix_relay_domains_service` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=254 DEFAULT CHARSET=latin1
```

or are you talking about once the migration fails? It looks like the `name` column gets dropped somewhere in there. Swapping to Postgres seems quite nice at the moment for atomic migrations :)

**Comment by tonioo** [comment]
Yes, once the migration fails. Indeed, the name column is dropped but a the domain_id one is added and filled by the 0003 migration, so the one just before 0004.

**Comment by tonioo** [comment]
@andrewyager What about this issue ?

**Comment by andrewyager** [comment]
Hi sorry; haven' thad a chance to come back to this. Is swapping to Postgres the recommended fix for now? :) If so, will work out how to make that happen.

**Comment by tonioo** [comment]
Hi, I don'tif switching to postgres would fix this issue... Any news on your side ?
