### ISSUE TITLE
install fail 

### ISSUE THREAD

**Issue by wangshunping** [tonioo/modoboa#809]
I can't install ...

```
$ git clone https://github.com/modoboa/modoboa-installer
$ cd modoboa-installer
$ sudo ./run.py 127.0.0.1
```

error info 

```
Welcome to Modoboa installer!
Your mail server 127.0.0.1 will be installed with the following components:
modoboa amavis clamav dovecot nginx razor postfix spamassassin uwsgi
Do you confirm? (Y/n) y
The process can be long, feel free to take a coffee and come back later ;)
Starting...
Installing modoboa
Traceback (most recent call last):
  File "run.py", line 64, in <module>
    main()
  File "run.py", line 54, in main
    scripts.install("modoboa", config)
  File "/Users/guo/Code/repository/03.original_code/modoboa-installer/modoboa_installer/scripts/__init__.py", line 21, in install
    getattr(script, appname.capitalize())(config).run()
  File "/Users/guo/Code/repository/03.original_code/modoboa-installer/modoboa_installer/scripts/base.py", line 138, in run
    self.post_run()
  File "/Users/guo/Code/repository/03.original_code/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 114, in post_run
    self.apply_settings()
  File "/Users/guo/Code/repository/03.original_code/modoboa-installer/modoboa_installer/scripts/modoboa.py", line 90, in apply_settings
    pw = pwd.getpwnam(self.user)
KeyError: 'getpwnam(): name not found: modoboa'
```

**Comment by tonioo** [comment]
Hi, could you please report issues related to the installer inside the appropriate repo ? (https://github.com/modoboa/modoboa-installer)
Try to run the installer using the --debug option.
