### ISSUE TITLE
deploy fail 

### ISSUE THREAD

**Issue by wangshunping** [tonioo/modoboa#810]
I install this repo by pip.

when i deploy this , there is error message.

```
guo@pingdeMacBook-Air-2 03.original_code$ sudo modoboa-admin.py deploy my_mail
Configuring database connection: default
Database type (mysql, postgres or sqlite3): sqlite3
What will be the hostname used to access Modoboa?
usage: manage.py set_default_site [-h] [--version] [-v {0,1,2,3}]
                                  [--settings SETTINGS]
                                  [--pythonpath PYTHONPATH] [--traceback]
                                  [--no-color]
manage.py set_default_site: error: unrecognized arguments: localhost

python manage.py set_default_site localhost failed, check your configuration
```

How can i fix it ?

**Comment by tonioo** [comment]
Looking at you example, you've not replied to the hostname question, right ?

**Comment by T-Grave** [comment]
I'm experiencing the same issue and I did reply to the question (as did he, with localhost), I replied with my external hostname, but it says it can't recognize the argument supplied (the hostname), looks like a bug in the script to me

**Comment by tonioo** [comment]
@T-Grave Which OS ?

**Comment by T-Grave** [comment]
Ubuntu 14.04

**Comment by haolle** [comment]
Hi guys, not sure if it is a bug.  It is a fresh env: python3.5.4 + modoboa1.10.3
It fails when running deploy instance command:

$ modoboa-admin.py deploy instance --collectstatic --domain mail.peop.com --dburl default:postgres://dev:dev@localhost:5432/peopmail

Traceback (most recent call last):
  File "/home/dd/anaconda3/envs/py35mail/bin/modoboa-admin.py", line 9, in <module>
    handle_command_line()
  File "/home/dd/anaconda3/envs/py35mail/lib/python3.5/site-packages/modoboa/core/commands/__init__.py", line 87, in handle_command_line
    commands = scan_for_commands()
  File "/home/dd/anaconda3/envs/py35mail/lib/python3.5/site-packages/modoboa/core/commands/__init__.py", line 70, in scan_for_commands
    [smart_str(cmdname)])
  File "/home/dd/anaconda3/envs/py35mail/lib/python3.5/site-packages/modoboa/core/commands/deploy.py", line 27, in <module>
    import pip
  File "/home/dd/anaconda3/envs/py35mail/lib/python3.5/site-packages/pip/__init__.py", line 45, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/dd/anaconda3/envs/py35mail/lib/python3.5/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/home/dd/anaconda3/envs/py35mail/lib/python3.5/site-packages/pip/download.py", line 40, in <module>
    from pip._vendor import requests, six
  File "/home/dd/anaconda3/envs/py35mail/lib/python3.5/site-packages/pip/_vendor/requests/__init__.py", line 98, in <module>
    from . import packages
  File "/home/dd/anaconda3/envs/py35mail/lib/python3.5/site-packages/pip/_vendor/requests/packages.py", line 12, in <module>
    sys.modules['pip._vendor.requests.packages.' + mod] = sys.modules["pip._vendor." + mod]
KeyError: 'pip._vendor.urllib3.contrib'

any idea about this failure? many thanks.
