### ISSUE TITLE
"Table 'modoboa.postfix_relay_domains_service' doesn't exist"

### ISSUE THREAD

**Issue by csmk** [tonioo/modoboa#815]
Hello Antoine,

I updated modoba 1.4.1 to 1.4.2, but when I try to deploy a new instance, I got the following error:

```
modoboa-admin.py deploy mdb --collectstatic --dburl default:mysql://modoboa:[PASSWORD]@localhost/modoboa amavis:mysql://amavis:[PASSWORD]@localhost/amavis --domain mail.domain.org --extensions modoboa_amavis modoboa_stats
Requirement already satisfied (use --upgrade to upgrade): modoboa-amavis in ./venv/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): modoboa-stats in ./venv/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): modoboa>=1.4.0 in ./venv/lib/python2.7/site-packages (from modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): chardet in ./venv/lib/python2.7/site-packages (from modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): lxml in ./venv/lib/python2.7/site-packages (from modoboa-stats)
Requirement already satisfied (use --upgrade to upgrade): djangorestframework==3.3.1 in ./venv/lib/python2.7/site-packages (from modoboa>=1.4.0->modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): passlib in ./venv/lib/python2.7/site-packages (from modoboa>=1.4.0->modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): django==1.8.7 in ./venv/lib/python2.7/site-packages (from modoboa>=1.4.0->modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): progressbar==2.3 in ./venv/lib/python2.7/site-packages (from modoboa>=1.4.0->modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): argparse in ./venv/lib/python2.7/site-packages (from modoboa>=1.4.0->modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): django-passwords==0.3.4 in ./venv/lib/python2.7/site-packages (from modoboa>=1.4.0->modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): factory-boy>=2.4 in ./venv/lib/python2.7/site-packages (from modoboa>=1.4.0->modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): django-reversion==1.9.3 in ./venv/lib/python2.7/site-packages (from modoboa>=1.4.0->modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): dj-database-url in ./venv/lib/python2.7/site-packages (from modoboa>=1.4.0->modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): pycrypto in ./venv/lib/python2.7/site-packages (from modoboa>=1.4.0->modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): django-xforwardedfor-middleware in ./venv/lib/python2.7/site-packages (from modoboa>=1.4.0->modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): rfc6266 in ./venv/lib/python2.7/site-packages (from modoboa>=1.4.0->modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): django-versionfield2>=0.3.3 in ./venv/lib/python2.7/site-packages (from modoboa>=1.4.0->modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): requests in ./venv/lib/python2.7/site-packages (from modoboa>=1.4.0->modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): fake-factory>=0.5.0 in ./venv/lib/python2.7/site-packages (from factory-boy>=2.4->modoboa>=1.4.0->modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): LEPL in ./venv/lib/python2.7/site-packages (from rfc6266->modoboa>=1.4.0->modoboa-amavis)
Requirement already satisfied (use --upgrade to upgrade): six>=1.9.0 in ./venv/lib/python2.7/site-packages (from django-versionfield2>=0.3.3->modoboa>=1.4.0->modoboa-amavis)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/modoboa/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/home/modoboa/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/modoboa/venv/lib/python2.7/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/modoboa/venv/lib/python2.7/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/home/modoboa/venv/lib/python2.7/site-packages/modoboa/core/management/commands/load_initial_data.py", line 49, in handle
    relay_models.Service.objects.get_or_create(name=service_name)
  File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/models/query.py", line 405, in get_or_create
    return self.get(**lookup), False
  File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/home/modoboa/venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/modoboa/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
django.db.utils.ProgrammingError: (1146, "Table 'modoboa.postfix_relay_domains_service' doesn't exist")

python manage.py load_initial_data  failed, check your configuration
```

Please, how I can fix the table issue?

Thank you in advance for your attention on this matter.

**Comment by tonioo** [comment]
Hi,

can you paste the content of the settings.py file somewhere ?

**Comment by csmk** [comment]
:point_right: https://gist.github.com/csmk/4203f8b34544d45071a4

**Comment by tonioo** [comment]
Hum, everything looks fine... Does it happen on a fresh deploy only ?

**Comment by csmk** [comment]
Yes.

After checking mysql tables, there was no table called "postfix_relay_domains_service". Isn't because of this? I've never used the extension "modoboa_admin_relaydomains", though I did the migration from 1.3.5 to 1.4.1 correctly.

**Comment by tonioo** [comment]
Hum, looks like the migration procedure does not handle this case :p

Can you do the following please:
* Remove all records related to app 'relaydomains' from the django_migrations table
* Run this command : ```python manage.py migrate relaydomains```
?

**Comment by csmk** [comment]
:+1: 

After I run the command above, the tables `postfix_relay_domains_relaydomain` and `postfix_relay_domains_service` was created successfully. The installation of the new instance is working fine too. But now there is another similar problem, when I try to add a new alias, I got this:

```
ProgrammingError at /aliases/new/
(1146, "Table 'modoboa.limits_limitspool' doesn't exist")

Request Method: GET
Request URL: https://mail.cmsrv.org/aliases/new/
Django Version: 1.8.7
Python Executable: /usr/bin/uwsgi
Python Version: 2.7.11
Python Path: ['.', '', '/home/modoboa/venv/lib64/python27.zip', '/home/modoboa/venv/lib64/python2.7'
, '/home/modoboa/venv/lib64/python2.7/plat-linux2', '/home/modoboa/venv/lib64/python2.7/lib-tk', '/home
/modoboa/venv/lib64/python2.7/lib-old', '/home/modoboa/venv/lib64/python2.7/lib-dynload', '/usr/lib64
/python2.7', '/usr/lib/python2.7/plat-linux2', '/home/modoboa/venv/lib/python2.7/site-packages']
Server time:
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'reversion',
 'rest_framework.authtoken',
 'modoboa',
 'modoboa.core',
 'modoboa.lib',
 'modoboa.admin',
 'modoboa.relaydomains',
 'modoboa.limits',
 'modoboa_amavis',
 'modoboa_stats')
Installed Middleware:
('x_forwarded_for.middleware.XForwardedForMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'modoboa.lib.middleware.AjaxLoginRedirect',
 'modoboa.lib.middleware.CommonExceptionCatcher',
 'modoboa.lib.middleware.RequestCatcherMiddleware')

Traceback:
File "/home/modoboa/venv/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  132.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/modoboa/venv/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  145.                     return func(*args, **kwargs)
File "/home/modoboa/venv/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  145.                     return func(*args, **kwargs)
File "/home/modoboa/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view

  22.                 return view_func(request, *args, **kwargs)
File "/home/modoboa/venv/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view

  22.                 return view_func(request, *args, **kwargs)
File "/home/modoboa/venv/lib/python2.7/site-packages/reversion/revisions.py" in do_revision_context
  323.                 return func(*args, **kwargs)
File "/home/modoboa/venv/lib/python2.7/site-packages/modoboa/admin/views/alias.py" in newalias
  77.         _("Alias created")
File "/home/modoboa/venv/lib/python2.7/site-packages/modoboa/admin/views/alias.py" in _new_alias
  39.     events.raiseEvent("CanCreate", request.user, "mailbox_aliases")
File "/home/modoboa/venv/lib/python2.7/site-packages/modoboa/lib/events.py" in raiseEvent
  90.         callback(*args, **kwargs)
File "/home/modoboa/venv/lib/python2.7/site-packages/modoboa/limits/controls.py" in can_create_new_object

  117.     check_limit(user, '%s_limit' % objtype, count)
File "/home/modoboa/venv/lib/python2.7/site-packages/modoboa/limits/controls.py" in check_limit
  28.         if user.limitspool.will_be_reached(lname, count):
File "/home/modoboa/venv/lib/python2.7/site-packages/django/utils/functional.py" in inner
  226.         return func(self._wrapped, *args)
File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/models/fields/related.py" in __get__
  473.                     rel_obj = self.get_queryset(instance=instance).get(**params)
File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/models/query.py" in get
  328.         num = len(clone)
File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/models/query.py" in __len__
  144.         self._fetch_all()
File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/models/query.py" in _fetch_all
  965.             self._result_cache = list(self.iterator())
File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/models/query.py" in iterator
  238.         results = compiler.execute_sql()
File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py" in execute_sql

  840.             cursor.execute(sql, params)
File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
  79.             return super(CursorDebugWrapper, self).execute(sql, params)
File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)
File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/utils.py" in __exit__
  98.                 six.reraise(dj_exc_type, dj_exc_value, traceback)
File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/backends/utils.py" in execute
  64.                 return self.cursor.execute(sql, params)
File "/home/modoboa/venv/lib/python2.7/site-packages/django/db/backends/mysql/base.py" in execute
  124.             return self.cursor.execute(query, args)
File "/home/modoboa/venv/lib/python2.7/site-packages/MySQLdb/cursors.py" in execute
  205.             self.errorhandler(self, exc, value)
File "/home/modoboa/venv/lib/python2.7/site-packages/MySQLdb/connections.py" in defaulterrorhandler
  36.     raise errorclass, errorvalue

Exception Type: ProgrammingError at /aliases/new/
Exception Value: (1146, "Table 'modoboa.limits_limitspool' doesn't exist")
Request information:
GET: No GET data

POST: No POST data

FILES: No FILES data
```

Do you think I should remove the "limit" from the django_migrations and then run the command `python manage.py migrate limits`?

**Comment by tonioo** [comment]
Yes, same fix with limits application :)

**Comment by csmk** [comment]
The tables `limits_limit` and `limits_limitspool` was created. Now everything is fine. Thank you for your support, antonie!

Have a nice day. ;)
