### ISSUE TITLE
Unable to login after install

### ISSUE THREAD

**Issue by padred123** [tonioo/modoboa#877]
Core_users table is empty

`Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/management/commands/load_initial_data.py", line 31, in handle
    admin.set_password("password")
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/core/models.py", line 164, in set_password
    "PasswordUpdated", self, raw_value, self.pk is None
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/lib/events.py", line 90, in raiseEvent
    callback(*args, **kwargs)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_pdfcredentials/modo_extension.py", line 39, in password_updated
    credentials(account, raw_password)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_pdfcredentials/documents.py", line 54, in credentials
    story.append(resized_image(imgpath + "/modoboa.png", 6*cm))
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa_pdfcredentials/documents.py", line 32, in resized_image
    img = utils.ImageReader(path)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/reportlab/lib/utils.py", line 807, in __init__
    annotateException('\nfileName=%r identity=%s'%(fileName,self.identity()))
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/reportlab/lib/utils.py", line 1387, in annotateException
    rl_reraise(t,v,b)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/reportlab/lib/utils.py", line 771, in __init__
    self.fp = open_for_read(fileName,'b')
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/reportlab/lib/utils.py", line 669, in open_for_read
    raise IOError('Cannot open resource "%s"' % name)
IOError: Cannot open resource "/srv/modoboa/instance/sitestatic/css/modoboa.png"
fileName='/srv/modoboa/instance/sitestatic/css/modoboa.png' identity=[ImageReader@0x7f8380b03bd0 filename='/srv/modoboa/instance/sitestatic/css/modoboa.png']`

**Comment by tonioo** [comment]
@padred123 Have you tried recently ?

**Comment by padred123** [comment]
Yes right before I posted this I did a `git clone https://github.com/modoboa/modoboa-installer` and reran the installation. My Ubuntu 14.04 isn't fresh so maybe something is throwing it off but all of the dependencies appeared to install correctly.

**Comment by almereyda** [comment]
Yes, you have to upgrade your dependencies as described in https://github.com/modoboa/modoboa-installer/issues/39, if that helps.

**Comment by padred123** [comment]
@almereyda Worked like charm! Thx!
