### ISSUE TITLE
python manage.py migrate cant migrate limits

### ISSUE THREAD

**Issue by blendi-93** [tonioo/modoboa#889]
hello its me again :( sry,

i have another modoboa instance broken, its no real issue from ur code but mby u can help me.

someone upped modoboa to version 1.5.3 and i get internal errors now as i try to access users, i tried python manage.py migrate and got:

    Operations to perform:
      Apply all migrations: authtoken, core, limits, lib, sessions, admin, modoboa_postfix_autoreply, auth, sites, reversion, contenttypes, modoboa_amavis, modoboa_imap_migration, relaydomains
    Running migrations:
      Rendering model states... DONE
      Applying limits.0003_auto_20160413_1046...Traceback (most recent call last):
      File "manage.py", line 10, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
        output = self.handle(*args, **options)
      File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/migrate.py", line 200, in handle
        executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
      File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 92, in migrate
        self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
      File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
        state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
      File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/executor.py", line 198, in apply_migration
        state = migration.apply(state, schema_editor)
      File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/migration.py", line 120, in apply
        operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
      File "/usr/local/lib/python2.7/dist-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
        self.code(from_state.apps, schema_editor)
      File "/usr/local/lib/python2.7/dist-packages/modoboa/limits/migrations/0003_auto_20160413_1046.py", line 40, in move_limits_to_user
        content_type=name_to_content_type[limit.name])
    KeyError: u'relay_domain_aliases_limit'

and i cant say from which version and how the customer uppgraded.

any ideas pls.
thx
matthias

**Comment by tonioo** [comment]
You need to clean the limits_limit table. Remove all entries with a name starting with 'relay_domain'.

**Comment by blendi-93** [comment]
its not only relay_domain so i have to clean them all and it shuld work?


thx i'll try it tonight

**Comment by tonioo** [comment]
If you remove the relay_domain entries, then the migration will work as expected. You can also remove all entries but you'll lost existing limits...

**Comment by blendi-93** [comment]
thx solved 50%.

for the other 50% i had to change "/usr/local/lib/python2.7/dist-packages/modoboa_amavis/modo_extension.py" line 45

replaced some code:

    #domalias_pattern = "@{0}".format(domalias.name) <= replaced with next line
    domalias_pattern = "@{0}".format(domalias.name.encode('utf-8'))

anyway thx for ur support and great software.
