### ISSUE TITLE
manage.py modo check_mx gives ValueError for one domain

### ISSUE THREAD

**Issue by karimelc** [tonioo/modoboa#920]
Hi,

I'm getting a ValueError for one of my domains when running manage.py modo check_mx. I can't see any difference bwtween the MX reord of this domain compared to all other domains. This is the output from the manage.py modo check_mx command:

Traceback (most recent call last):
  File "/opt/modoboa_home/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/subcommand/base.py", line 53, in run_from_argv
    return super(SubcommandCommand, self).run_from_argv(argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/subcommand/base.py", line 84, in handle
    return command.run_from_argv(argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 241, in handle
    self.check_domain(domain, **options)
  File "/usr/local/lib/python2.7/dist-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 217, in check_domain
    self.check_valid_mx(domain, mx_list, **options)
  File "/usr/local/lib/python2.7/dist-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 173, in check_valid_mx
    for mx in mx_list]
  File "/usr/lib/python2.7/dist-packages/ipaddress.py", line 166, in ip_address
    address)
ValueError: u'mail.olearys.ae.' does not appear to be an IPv4 or IPv6 address

**Comment by karimelc** [comment]
I found the problem, I had two MX entries for the domain where it bombs out. I'll just close this issue.
