### ISSUE TITLE
Cron $PYTHON $INSTANCE/manage.py modo check_mx giving error (Debian)

### ISSUE THREAD

**Issue by abmiller99** [tonioo/modoboa#941]
This default Cron job giving me an error:

Modoboa 1.6.0 on Debian 8 (Jessie)

```
Traceback (most recent call last):
  File "/srv/modoboa/instance/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/subcommand/base.py", line 53, in run_from_argv
    return super(SubcommandCommand, self).run_from_argv(argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/subcommand/base.py", line 84, in handle
    return command.run_from_argv(argv)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 241, in handle
    self.check_domain(domain, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 217, in check_domain
    self.check_valid_mx(domain, mx_list, **options)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 174, in check_valid_mx
    valid_mxs = self.valid_mxs
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/modoboa/admin/management/commands/subcommands/_mx.py", line 46, in valid_mxs
    for v in valid_mxs.split() if v.strip()]
  File "/srv/modoboa/env/local/lib/python2.7/site-packages/ipaddress.py", line 202, in ip_network
    address)
ValueError: u'mail.brightwood.ie' does not appear to be an IPv4 or IPv6 network
```

**Comment by gawel** [comment]
Try to upgrade to 1.6.1. I remember making a few improvements on this subject. Not sure if those are in 1.6.0

**Comment by tonioo** [comment]
No, they are not.

**Comment by abmiller99** [comment]
Actually I have been working on upgrading to 1.6.1 with @tonioo over on issue #939. I am still at 1.6.0. Can't get 1.6.1 to take. My last comment has the process I am using. Thanks for all your help guys. Great product so far.

**Comment by tonioo** [comment]
@abmiller99 Is it better with 1.6.1 ?

**Comment by abmiller99** [comment]
Seems to be fixed - yes.
